### ISSUE TITLE
Use --datadir=$PREFIX/share

### ISSUE THREAD

**Issue by peterjc** [conda-forge/file-feedstock#4]
In https://github.com/bioconda/bioconda-recipes/pull/8382 @lucventurini proposed adding  ``--datadir=$PREFIX/share`` in the ``build.sh`` configuration step

**Comment by mrakitin** [comment]
Implemented by @chrisburr via https://github.com/conda-forge/file-feedstock/pull/2/files#diff-44a73bcc045c193c3bd45da87994b03bR5 (https://github.com/conda-forge/file-feedstock/pull/2). Proposing closing.
